#!/usr/bin/env bash
#
# Regenerate the prebuilt-binary Homebrew formula in mascah/homebrew-tap to point
# at the archives goreleaser just published for this release, then push it.
#
# goreleaser removed formula generation (`brews`) in v2.16, so we own the .rb
# ourselves. This keeps `brew install mascah/tap/nerve` (a formula, not a cask):
# formulae don't quarantine the binary, so there's no Gatekeeper/xattr hack, and
# it installs a prebuilt binary on macOS and Linux alike (no compile, no Go
# toolchain). Run from the release workflow AFTER goreleaser has uploaded the
# archives + checksums.txt to the release.
#
# Usage:   scripts/update-tap-formula.sh <tag>          (e.g. v0.2.0)
# Env:
#   GH_TOKEN / GITHUB_TOKEN     read this repo's release assets via `gh`
#   HOMEBREW_TAP_GITHUB_TOKEN   PAT with contents:write on mascah/homebrew-tap
set -euo pipefail

TAG="${1:?usage: update-tap-formula.sh <tag>}"
VERSION="${TAG#v}"

REPO="mascah/nerve"
TAP_REPO="mascah/homebrew-tap"
FORMULA_PATH="Formula/nerve.rb"
BASE_URL="https://github.com/${REPO}/releases/download/${TAG}"

: "${HOMEBREW_TAP_GITHUB_TOKEN:?HOMEBREW_TAP_GITHUB_TOKEN is required}"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

# goreleaser already computed every archive's sha256 into checksums.txt and
# uploaded it to the release — fetch and parse it rather than re-downloading.
gh release download "$TAG" --repo "$REPO" --pattern checksums.txt --dir "$workdir"

sha() { awk -v f="nerve_${VERSION}_$1.tar.gz" '$2 == f { print $1 }' "$workdir/checksums.txt"; }
darwin_arm64="$(sha darwin_arm64)"
darwin_amd64="$(sha darwin_amd64)"
linux_arm64="$(sha linux_arm64)"
linux_amd64="$(sha linux_amd64)"

for pair in \
  "darwin_arm64:$darwin_arm64" "darwin_amd64:$darwin_amd64" \
  "linux_arm64:$linux_arm64" "linux_amd64:$linux_amd64"; do
  if [ -z "${pair#*:}" ]; then
    echo "error: no sha256 for nerve_${VERSION}_${pair%%:*}.tar.gz in checksums.txt" >&2
    exit 1
  fi
done

git clone --depth 1 \
  "https://x-access-token:${HOMEBREW_TAP_GITHUB_TOKEN}@github.com/${TAP_REPO}.git" \
  "$workdir/tap"

mkdir -p "$workdir/tap/$(dirname "$FORMULA_PATH")"
cat > "$workdir/tap/$FORMULA_PATH" <<EOF
# This file is generated by nerve's release workflow (scripts/update-tap-formula.sh).
# DO NOT EDIT by hand — changes will be overwritten on the next release.
class Nerve < Formula
  desc "Git-worktree manager that allocates ports and wires up Claude Code hooks"
  homepage "https://github.com/mascah/nerve"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE_URL}/nerve_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    end
    on_intel do
      url "${BASE_URL}/nerve_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/nerve_${VERSION}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
    on_intel do
      url "${BASE_URL}/nerve_${VERSION}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
  end

  def install
    bin.install "nerve"
  end

  test do
    assert_match "${VERSION}", shell_output("#{bin}/nerve version")
  end
end
EOF

cd "$workdir/tap"
git config user.name "goreleaser-bot"
git config user.email "goreleaser-bot@users.noreply.github.com"
git add "$FORMULA_PATH"
if git diff --cached --quiet; then
  echo "formula already up to date for ${TAG}"
  exit 0
fi
git commit -m "nerve ${VERSION}"
git push origin HEAD
echo "pushed ${FORMULA_PATH} for ${TAG} to ${TAP_REPO}"
